[project]
name = "ftm-random"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.1",
    "faker>=40.5.1",
    "followthemoney>=4.5.3",
]

[project.scripts]
ftm-random = "ftm-random:main"